# Generated by Django 3.1 on 2021-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('Mca', 'Mca'), ('Mtech', 'Mtech'), ('Mba', 'Mba'), ('Btech', 'Btech')], max_length=50)),
            ],
        ),
    ]
